In [1]:
import numpy as np
import pandas as pd

### Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
    HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [2]:
x = np.array([1,2,3,4,5])
N = 3
np.vander(x,N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [3]:
N=4
np.vander(x,N)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1]])

In [4]:
N=4
np.vander(x,N, increasing=False)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1]])

In [5]:
N=4
np.vander(x,N, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   4,  16,  64],
       [  1,   5,  25, 125]])

In [6]:
# When 'N' is not given, square array will return.
np.vander(x)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [7]:
np.vander(x, increasing=False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [8]:
#The determinant of a square Vandermonde matrix is the product of the differences between the values of the input vector
# (5-4)*(5-3)*(5-2)*(5-1)*(4-3)*(4-2)*(4-1)*(3-2)*(3-1)*(2-1)
print(np.linalg.det(np.vander(x)))
print()
print('-'*80)

287.9999999999965

--------------------------------------------------------------------------------


### Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: The moving average sequence has n-k+1 elements as shown below. The moving averages with k=4 of a ten-value sequence (n=10) is shown below

    i 1 2 3 4 5 6 7 8 9 10
    ===== == == == == == == == == == ==
    Input 10 20 30 40 50 60 70 80 90 100
    y1 25 = (10+20+30+40)/4
    y2 35 = (20+30+40+50)/4
    y3 45 = (30+40+50+60)/4
    y4 55 = (40+50+60+70)/4
    y5 65 = (50+60+70+80)/4
    y6 75 = (60+70+80+90)/4
    y7 85 = (70+80+90+100)/4
    
### Thus, the moving average sequence has n-k+1=10-4+1=7 values.
### Question: Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [9]:
arr = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
win_size = 3

arr_series = pd.Series(arr)
windows = arr_series.rolling(win_size)
moving_averages = windows.mean()

moving_averages_list = moving_averages.tolist()
without_nan = moving_averages_list[win_size - 1:]

print(moving_averages)
print()
print(moving_averages_list)
print()
print(without_nan)

0            NaN
1            NaN
2       5.000000
3       4.666667
4       5.666667
5       6.666667
6       9.666667
7      28.666667
8      49.333333
9      72.666667
10     84.000000
11     93.333333
12    116.333333
dtype: float64

[nan, nan, 5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
